services:
  terraform:
    image: hashicorp/terraform:1.6.2
    volumes:
      - ./setup:/tf/setup
      - ./deploy:/tf/deploy
    working_dir: /tf
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=us-east-1
      - TF_WORKSPACE=${TF_WORKSPACE}
      - TF_VAR_auth_secret=${AUTH_SECRET}
      - TF_VAR_az_client_id=${TF_VAR_AZ_CLIENT_ID}
      - TF_VAR_az_tenant_id=${TF_VAR_AZ_TENANT_ID}
      #- TF_VAR_users_table=${TF_VAR_users_table}
      - TF_VAR_users_table=${users_table}
      - TF_VAR_db_password=${TF_VAR_DB_PASSWORD}
      #- TF_VAR_db_password=${TF_VAR_db_password} 
      #- TF_VAR_django_secret_key=${TF_VAR_django_secret_key}
      - TF_VAR_django_secret_key=${TF_VAR_django_secret_key}
      - TF_VAR_ecr_proxy_image=${TF_VAR_ecr_proxy_image}
      - TF_VAR_ecr_app_image=${TF_VAR_ecr_app_image}
      - TF_VAR_ecr_tools_image=${TF_VAR_ecr_tools_image}
      - TF_VAR_cd_github_access_token=${TF_VAR_cd_github_access_token}